//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace regtr
{
    using System;
    using System.Collections.Generic;
    
    public partial class bd
    {
        public string log { get; set; }
        public string pass { get; set; }
    
        public virtual auth auth { get; set; }
    }
}
