//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace regtr
{
    using System;
    using System.Collections.Generic;
    
    public partial class Marshrut
    {
        public Marshrut()
        {
            this.Perevozka = new HashSet<Perevozka>();
        }
    
        public int ID_Marshrut { get; set; }
        public string Номер_маршрута { get; set; }
        public string Пункт_назначения { get; set; }
        public string Район { get; set; }
        public string Область { get; set; }
        public int Расстояние { get; set; }
        public int Вес { get; set; }
        public System.DateTime Время_отправки { get; set; }
        public System.DateTime Время_прибытия { get; set; }
    
        public virtual ICollection<Perevozka> Perevozka { get; set; }
    }
}
