//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace regtr
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class hachiuebani123 : DbContext
    {
        public hachiuebani123()
            : base("name=hachiuebani123")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<auth> auth { get; set; }
        public DbSet<Avtobus> Avtobus { get; set; }
        public DbSet<Bilet> Bilet { get; set; }
        public DbSet<Dispetcher> Dispetcher { get; set; }
        public DbSet<Marshrut> Marshrut { get; set; }
        public DbSet<Perevozka> Perevozka { get; set; }
        public DbSet<sysdiagrams> sysdiagrams { get; set; }
        public DbSet<Voditel> Voditel { get; set; }
        public DbSet<bd> bd { get; set; }
    }
}
